stages:
  - lint
  - test

variables:
  DOCKER_TLS_CERTDIR: "/certs"

image: harbor.pg.innopolis.university/demo_docker_ci_blxxdclxud/docker:stable-dind

linting:
  stage: lint
  image: harbor.pg.innopolis.university/demo_docker_ci_blxxdclxud/golangci/golangci-lint

  script:
    - golangci-lint run ./backend


testing:
  stage: test
  image: harbor.pg.innopolis.university/demo_docker_ci_blxxdclxud/golang:1.21
  script:
    - go mod tidy
    - go test -v ./backend

