stages:
  - lint
  - test

image: docker:latest

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

linting:
  stage: lint
  image: golangci/golangci-lint:v1.44
  script:
    - golangci-lint run ./backend
  tags:
    - docker

testing:
  needs:
    - lint
  stage: test
  image: golang:1.21
  script:
    - go test -v ./backend/tests
  tags:
    - docker
