stages:
  - lint
  - test

variables:
  DOCKER_TLS_CERTDIR: "/certs"

image: harbor.pg.innopolis.university/demo_docker_ci_blxxdclxud/docker:stable-dind

services:
  - name: harbor.pg.innopolis.university/demo_docker_ci_blxxdclxud/docker:stable-dind
    alias: docker

linting:
  stage: lint
  before_script:
    - echo "$HARBOR_PASSWORD" | docker login -u "$HARBOR_USERNAME" "$HARBOR_HOST" --password-stdin
  image: harbor.pg.innopolis.university/demo_docker_ci_blxxdclxud/golangci/golangci-lint

  script:
    - golangci-lint run ./backend


testing:
  stage: test
  before_script:
    - echo "$HARBOR_PASSWORD" | docker login -u "$HARBOR_USERNAME" "$HARBOR_HOST" --password-stdin
  image: harbor.pg.innopolis.university/demo_docker_ci_blxxdclxud/golang:1.21
  script:
    - go test -v ./backend/tests

